# A workflow that tests this action

name: SARIF comment workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Run the SARIF PR commenter

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28

      - name: Post SARIF findings in the pull request
        if: github.event_name == 'pull_request'
        uses: tomwillis608/sarif-to-comment-action@issue/3/owasp-dependency-check
        with:
            token:      ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            branch:     ${{ github.head_ref }}
            pr-number:  ${{ github.event.number }}
            sarif-file: "./test/fixtures/odc.sarif"
            title:      "Test comment with security scanning results"
            dry-run:    'false'
            odc-sarif: true
