# A workflow that tests this action

name: SARIF comment workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    name: Run the SARIF PR commenter

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Post SARIF findings in the pull request
        if: github.event_name == 'pull_request'
        uses: tomwillis608/sarif-to-comment-action@issue/3/owasp-dependency-check
        with:
            token:      ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            branch:     ${{ github.head_ref }}
            pr-number:  ${{ github.event.number }}
            sarif-file: "./test/fixtures/odc.sarif"
            title:      "Test comment with security scanning results"
            dry-run:    'false'
            odc-sarif: true
